version: '3.8'

services:
  semantic-flow-analyzer:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./analysis_output:/app/analysis_output
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped