from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="semantic-flow-analyzer",
    version="0.1.0",
    author="Semantic Flow Research Team",
    author_email="contact@semanticflow.ai",
    description="A computational framework bridging NLP with complexity science to analyze semantic evolution",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/semanticflow/semantic-flow-analyzer",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "scikit-learn>=1.0.0",
        "pandas>=1.3.0",
        "networkx>=2.6.0",
        "plotly>=5.0.0",
        "umap-learn>=0.5.0",
        "hdbscan>=0.8.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "tqdm>=4.62.0",
        "joblib>=1.1.0",
        "pydantic>=1.8.0",
        "click>=8.0.0",
        "praw>=7.0.0",
        "sentence-transformers>=2.0.0",
        "transformers>=4.0.0",
        "torch>=1.9.0",
        "faiss-cpu>=1.7.0",
        "pyarrow>=5.0.0",
        "h5py>=3.3.0",
        "numba>=0.56.0",
        "dash>=2.0.0",
        "dash-bootstrap-components>=1.0.0",
        "python-dotenv>=0.19.0",
        "redis>=4.0.0",
        "sqlalchemy>=1.4.0",
        "psycopg2-binary>=2.9.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0.0",
            "pytest-cov>=2.12.0",
            "black>=21.6.0",
            "flake8>=3.9.0",
            "mypy>=0.910",
            "pre-commit>=2.15.0",
            "sphinx>=4.0.0",
            "sphinx-rtd-theme>=0.5.0",
        ],
        "gpu": [
            "faiss-gpu>=1.7.0",
            "cupy-cuda11x>=9.0.0",
        ],
        "full": [
            "jupyter>=1.0.0",
            "ipywidgets>=7.6.0",
            "bokeh>=2.3.0",
            "altair>=4.1.0",
            "streamlit>=1.0.0",
        ],
    },
    # entry_points={
    #     "console_scripts": [
    #         "sfa=sfa.cli:main",
    #     ],
    # },
)